### ISSUE TITLE
Windows VM loses static IP address after upgrading virtio-win drivers

### ISSUE THREAD

**Issue by nlarenti** [virtio-win/virtio-win-pkg-scripts#77]
**Describe the bug**
Windows VM loses static IP address after upgrading virtio-win drivers.

**To Reproduce**
Upgrading virtio-win drivers tried on Windows Server 2016/2019/2022

**Expected behavior**
Configuration of network adapter is not lost

**Screenshots**

**Host:**
 - Disto: Proxmox
 - Kernel Linux 6.2.9-1-pve

**Guest:**
 - Windows version
 - virtio-win version virtio-win-0.1.229.iso

**Comment by vrozenfe** [comment]
@nlarenti 

Thank you for reporting the issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1898985
We have a couple of similar bugs describing the same problem.
While we are looking for a proper solution to fix this issue.
Meanwhile, there are at least two workarounds that you
might find useful:
https://bugzilla.redhat.com/show_bug.cgi?id=1898985#c8
https://bugzilla.redhat.com/show_bug.cgi?id=1898985#c19

**Comment by vrozenfe** [comment]
@Hedius 

You need to run "netsh dump > filename.txt" command from the elevated cmd prompt before un-install
and restore the settings with  " netsh -f filename.txt" command after installing the new virtio-win package.

I also need to mention that recently we added a new custom action to virtio-win installer which designed to save and restore netkvm network settings automatically https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/ea0643ffb87c9cd8cf85dce02ea0cc22f64b549f

Best,
Vadim.

**Comment by Hedius** [comment]
> @Hedius
> 
> You need to run "netsh dump > filename.txt" command from the elevated cmd prompt before un-install and restore the settings with " netsh -f filename.txt" command after installing the new virtio-win package.
> 
> I also need to mention that recently we added a new custom action to virtio-win installer which designed to save and restore netkvm network settings automatically [virtio-win/virtio-win-guest-tools-installer@ea0643f](https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/ea0643ffb87c9cd8cf85dce02ea0cc22f64b549f)
> 
> Best, Vadim.

Thank you for the info!

Florian

**Comment by CHN-STUDENT** [comment]
I have same issue, when i open a c# program in server2016 vm, we lose all network connect.

**Comment by vrozenfe** [comment]
@CHN-STUDENT 
Not sure that your issue somehow related to this case.

This particular case is about loosing network interface settings while updating virtio-win package.
The problem has been solved with https://github.com/virtio-win/virtio-win-guest-tools-installer/pull/57
and should work fine on the latest virtio-win releases.

Best,
Vadim.

**Comment by cluck** [comment]
Still an issue with 0.1.285.

I just updated Windows Server 2019 from Virtio-win-guest-tools 0.1.185 to 0.1.285, and I see how adapters are actually **deleted and recreated** in the process, also changing its name from e.g. "Ethernet" to "Ethernet 2". The new adapter gets some configuration restored by the installer, but not the static IP address. Consequently, if I restore the IP address manually, Windows will warn and ask for confirmation that another adapter has the same IP address (but that old adapter isn't there yet).

The workaround I found is to update the NetKVM in advance directly via Windows (this will restart the interface, so be aware of this if you work remotely):
```
pnputil /add-driver F:\NetKVM\2k19\amd64\netkvm.inf /install
```

The installer can then be launched same as before, and while it will again restart the network interfaces, they won't be replaced or misconfigured.

**Comment by raidsec** [comment]
Are there any recommendation how to upgrade the virtio tool without loosing the network config. Use the custom action or the sh command? i am confused what is working / the recommended way.

**Comment by raidsec** [comment]
> [@Hedius](https://github.com/Hedius)
> 
> You need to run "netsh dump > filename.txt" command from the elevated cmd prompt before un-install and restore the settings with " netsh -f filename.txt" command after installing the new virtio-win package.
> 
> I also need to mention that recently we added a new custom action to virtio-win installer which designed to save and restore netkvm network settings automatically [virtio-win/virtio-win-guest-tools-installer@ea0643f](https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/ea0643ffb87c9cd8cf85dce02ea0cc22f64b549f)
> 
> Best, Vadim.

Its not working reliable. I have done that but after restart the its still set to static but no ips in the fields.

**Comment by debuglevel** [comment]
> You need to run "netsh dump > filename.txt" command from the elevated cmd prompt before un-install and restore the settings with " netsh -f filename.txt" command after installing the new virtio-win package.

Warning for localized Windows (at least Windows 2016): `netsh dump` adds localized strings into the dump...

```plain
add route prefix=0.0.0.0/0 interface="Ethernet 2" nexthop=10.131.32.1 publish=Ja
```
... which it does not understand on import:
```shell
Ungültiger publish-Parameter (Ja). Der Wert für "Publish" sollte "yes", "no" oder "age" lauten.
```

Also `netsh dump` tries to execute commands it does not even support:
```plain
Der Befehl "netsh advfirewall dump" ist in dieser Version von Windows nicht
implementiert. Verwenden Sie stattdessen den Befehl "netsh advfirewall export",
um die aktuelle Konfiguration der Windows-Firewall mit erweiterter Sicherheit
aus dem aktuellen Richtlinienspeicher in eine Datei auf dem Datentr„ger zu
schreiben. Die Datei kann anschlieáend mittels "netsh advfirewall import"
gelesen und in einen anderen Richtlinienspeicher (beispielsweise in ein
Gruppenrichtlinienobjekt oder in den aktuellen Richtlinienspeicher eines anderen
Computers) geschrieben werden. Verwenden Sie zum Festlegen des aktuellen
Richtlinienspeichers den Befehl "netsh advfirewall set store".
Weitere Informationen im Zusammenhang mit "netsh advfirewall" finden Sie in den
Netsh-Befehlen fr die Windows-Firewall mit erweiterter Sicherheit unter "http://go.microsoft.com/fwlink/?linkid=111237".pushd ipsecdosprotection
```

> Still an issue with 0.1.285.
Tested with 0.1.271 (because 285 seems to have other bugs :D) on Windows 2016.

> ```
> pnputil /add-driver F:\NetKVM\2k19\amd64\netkvm.inf /install
> ```
Worked for me.

> The installer can then be launched same as before, and while it will again restart the network interfaces, they won't be replaced or misconfigured.
For me, the installer still deleted my configuration.

Most unfortunately, there is no option in the installer like "do not touch NetKVM", but only "remove" and "install". "do not touch NetKVM" would be great, because then I could just update the network driver manually.

**Comment by cluck** [comment]
Depending on how ProductCode GUIDs, ProductVersion and the Component GUIDs change between MSI releases, MsiExec supports four types of upgrade paths, i.e. the default/fallback _major upgrade_, the _minor upgrade_, the rare _small upgrade_ based on MSP patch files, and the _small update_.

The MSIs released by Fedora all have different ProductCode GUIDs, thus MsiExec forces the _major upgrade_ path: it uninstalls the old components according to the old MSI stashed in %windir%\Installer, and then installs the new components by the new MSI.

The MSIs could be built so that MsiExec would take the _minor upgrade_ or even the _small update_ route. For a _minor upgrade_ the ProductCode needs to remain the same, and for a _small update_ even the Component GUIDs and _the ProductVersion_ must remain the same (fortunately it ignores the fourth, least-significant, component of ProductVersion though).

https://learn.microsoft.com/en-us/windows/win32/msi/minor-upgrades
https://learn.microsoft.com/en-us/windows/win32/msi/msienforceupgradecomponentrules

**Comment by YanVugenfirer** [comment]
@cluck for different historical reasons that was on purpose implementation.
Moving forward to next WiX tools version we are thinking to change that, but it will take time.

**Comment by cluck** [comment]
- https://github.com/virtio-win/virtio-win-guest-tools-installer/pull/92
- https://github.com/virtio-win/virtio-win-guest-tools-installer/pull/97

**Comment by cluck** [comment]
- https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1460
